In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [7]:
a.ndim

1

In [8]:
a = np.array([(1,2,3),(4,5,6)])

In [9]:
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
import sys

L = range(10000)
print(sys.getsizeof(5)*len(L))

280000


In [11]:
A = np.arange(10000)
print(A.itemsize * A.size)

80000


In [16]:
A

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a.itemsize

8

In [13]:
a.size

6

In [14]:
a.ndim

2

In [15]:
a.dtype

dtype('int64')

In [18]:
A = np.arange(10000,dtype='int8')
print(A.itemsize * A.size)

10000


In [24]:
import time

SIZE = 10000
L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [x+y for x,y in zip(L1,L2)]
end = time.time()
print((end - start)*1000)

1.6689300537109375


In [27]:
start = time.time()
result = A1+A2
end = time.time()
print((end - start)*1000)

0.32401084899902344


In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a.shape

(3, 3)

In [31]:
a[1,1]

5

In [33]:
a[1:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [34]:
a[:,2:]

array([[3],
       [6],
       [9]])

In [42]:
a = np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])

In [43]:
a

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [44]:
print(a)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9 10]]


In [45]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [46]:
a.size

12

In [48]:
a.min()

1

In [49]:
a.max()

10

In [50]:
a.sum()

62

In [52]:
a

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [53]:
a.sum(axis=0)

array([11, 14, 17, 20])

In [54]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766]])

In [56]:
np.std(a)

2.733536577809454

In [57]:
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [61]:
a - b

array([[0, 0, 0],
       [0, 0, 0]])

In [62]:
a * b # this is not array multiplication

array([[ 1,  4,  9],
       [16, 25, 36]])

In [63]:
a / b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.dot(a,b)  

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [64]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)])
d = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [65]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.dot(c,d)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [75]:
np.hstack((c,d))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [76]:
np.vstack((c,d))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
c.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.log(c)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [79]:
np.exp(c)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [80]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [83]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])